
import DBHandling.DBHandler;
import DTOs.Medicine;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adeel
 */
public class MedicineFrame extends javax.swing.JFrame {

    /**
     * Creates new form MedicineFrame
     */
    public MedicineFrame() {
        initComponents();
    }

    public DefaultTableModel displayMedicineData(){
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"ID","Medicine Name","Cost Price",
            "Sale Price","Stock","Company"});
        DBHandler db = new DBHandler();
        ArrayList<Medicine> ar = db.viewAllMedicines();
        int size = ar.size();
        for(int i=0;i<size;i++){
            model.addRow(new Object[]{ar.get(i).getId(),ar.get(i).getName(),
            ar.get(i).getCostPrice(),ar.get(i).getSalePrice(),ar.get(i).getAmount(),
            ar.get(i).getCompanyName()});
        }
        return model;
    }
    
    public void clearData(){
        nameTF.setText("");
        companyTF.setText("");
        phoneTF.setText("");
        emailTF.setText("");
        costTF.setText("");
        saleTF.setText("");
        stockTF.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headingLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nameLbl = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        costTF = new javax.swing.JTextField();
        costLbl = new javax.swing.JLabel();
        stockLbl = new javax.swing.JLabel();
        stockTF = new javax.swing.JTextField();
        saleTF = new javax.swing.JTextField();
        saleLbl = new javax.swing.JLabel();
        phoneLbl = new javax.swing.JLabel();
        phoneTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        companyLbl = new javax.swing.JLabel();
        companyTF = new javax.swing.JTextField();
        saveMedicineBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainPanel.setLayout(null);

        headingLbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        headingLbl.setText("Medicine Management");
        mainPanel.add(headingLbl);
        headingLbl.setBounds(10, 10, 270, 40);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Medicine Management", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 12))); // NOI18N

        nameLbl.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nameLbl.setText("Medicine Name:");

        nameTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        costTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        costLbl.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        costLbl.setText("Cost Per Unit:");

        stockLbl.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        stockLbl.setText("Stock:");

        stockTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        saleTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        saleLbl.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        saleLbl.setText("Sale Per Unit:");

        phoneLbl.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        phoneLbl.setText("Phone Number:");

        phoneTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        phoneTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTFActionPerformed(evt);
            }
        });

        emailTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        emailLbl.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        emailLbl.setText("Company Email:");

        companyLbl.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        companyLbl.setText("Company Name:");

        companyTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        saveMedicineBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        saveMedicineBtn.setText("Save Medicine");
        saveMedicineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMedicineBtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        table.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        table.setModel(displayMedicineData());
        table.getColumnModel().getColumn(0).setPreferredWidth(5);
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(nameLbl)
                                .addGap(26, 26, 26)
                                .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(costLbl)
                                .addGap(39, 39, 39)
                                .addComponent(costTF, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(saleLbl)
                                .addGap(40, 40, 40)
                                .addComponent(saleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(stockLbl)
                                .addGap(87, 87, 87)
                                .addComponent(stockTF))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(companyLbl)
                                .addGap(22, 22, 22)
                                .addComponent(companyTF))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(phoneLbl)
                                .addGap(28, 28, 28)
                                .addComponent(phoneTF))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(emailLbl)
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailTF)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(saveMedicineBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(cancelBtn)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(162, 162, 162))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(nameLbl))
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(costLbl))
                    .addComponent(costTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(saleLbl))
                    .addComponent(saleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(stockLbl))
                    .addComponent(stockTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(companyLbl))
                    .addComponent(companyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(phoneLbl))
                    .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(emailLbl))
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveMedicineBtn)
                    .addComponent(cancelBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(jPanel2);
        jPanel2.setBounds(10, 50, 750, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phoneTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTFActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void saveMedicineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMedicineBtnActionPerformed
        // TODO add your handling code here:
        String medicineName = nameTF.getText();
        String companyName = companyTF.getText();
        String phone = phoneTF.getText();
        String email = emailTF.getText();
        try {
            double costPrice = Double.parseDouble(costTF.getText());
            double salePrice = Double.parseDouble(saleTF.getText());
            int amount = Integer.parseInt(stockTF.getText());
            if(!medicineName.isEmpty() && !companyName.isEmpty() && 
                    !phone.isEmpty() && !email.isEmpty() && phone.matches("^[0-9]*$")){
                DBHandler db = new DBHandler();
                if(db.addNewMedicine(medicineName,companyName,phone,email,costPrice,
                        salePrice,amount)){
                    JOptionPane.showMessageDialog(mainPanel, "Successfully New Medicine Added");                
                    clearData();
                    table.setModel(displayMedicineData());
                    table.getColumnModel().getColumn(0).setPreferredWidth(5);
                    jScrollPane1.setViewportView(table);
                }
                else{
                    JOptionPane.showMessageDialog(mainPanel, "Failed to Add Medicine");
                    clearData();
                }
            }
            else{
                JOptionPane.showMessageDialog(mainPanel, "Please Enter all fields with valid information");
            }            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(mainPanel, "Failed to Add Medicine");
            clearData();
        }        
    }//GEN-LAST:event_saveMedicineBtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MedicineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MedicineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MedicineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MedicineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MedicineFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel companyLbl;
    private javax.swing.JTextField companyTF;
    private javax.swing.JLabel costLbl;
    private javax.swing.JTextField costTF;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel headingLbl;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JLabel saleLbl;
    private javax.swing.JTextField saleTF;
    private javax.swing.JButton saveMedicineBtn;
    private javax.swing.JLabel stockLbl;
    private javax.swing.JTextField stockTF;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
